services:
  server:
    build:
      context: ./server
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env

  client:
    build:
      context: ./client
    ports:
      - "8080:80"
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL:-http://localhost:3000}
